/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Anjalu Boro (https://sketchfab.com/anjaluboro435)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pepperfry-fn1680115-2e38a4b8434f4a88bd0bc10e3d354641
Title: Pepperfry FN1680115
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.035}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.394}>
            <mesh geometry={nodes.Bottom_wood_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.Back_wood_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.Top_wood_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.BLMagnetic_Steel_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.BRMagnetic_Steel_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.LSide_Wood_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.RSide_Wood_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.LF_Leg_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.LB_Leg_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.RF_Leg_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.RB_Leg_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.Top_Shelf_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.Middle_Shelf_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.L_WoodT_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.L_WoodB_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.L_WoodL_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.L_WoodR_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.L_Knob_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.LT_Hinge_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.LB_Hinge_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.L_Steel_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface71_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface70_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface68_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface59_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface56_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface58_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface57_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface60_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface61_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface73_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface62_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface63_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface74_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.R_WoodT_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.R_WoodL_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.R_WoodR_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.R_WoodB_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.R_Knob_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.RT_Hinge_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.RB_Hinge_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.R_Steel_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface74_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface63_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface62_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface73_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface61_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface60_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface57_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface58_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface56_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface59_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface68_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface70_lambert1_0_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface71_lambert1_0_1.geometry} material={materials.lambert1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
